services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeblood_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: ./Frontend/codeblood-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
