# Generated by Django 5.2.2 on 2025-06-15 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('high_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_id', to='game.player')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_name', to='game.player', to_field='player_name')),
            ],
        ),
    ]
