# Generated by Django 5.2.2 on 2025-06-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('high_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_id', to='game.player')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_name', to='game.player')),
            ],
        ),
    ]
