# Generated by Django 5.2.2 on 2025-06-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='player_name',
        ),
    ]
