# Generated by Django 5.2.2 on 2025-06-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_name', to='game.player', to_field='player_name'),
        ),
    ]
